### ISSUE TITLE
Introduce Draft Mode

### ISSUE THREAD

**Issue by ystxn** [finos/symphony-wdk#126]
### Description of Problem:
When building or revising a complex workflow, it is typically not in a useable / ready state for a while. In a traditional development cycle, developers will build and test code on their local devices before it gets deployed. In the WDK world, workflows are often live and edited as-is by users. This causes incomplete workflows to be deployed once they are saved and saving is the only way to validate the workflow contents at the moment.

### Potential Solutions:
Introduce a boolean `draft` (or `published` or `live`) field in SWADL that will trigger the validation process when a watched workflow gets saved, but does not deploy the workflow. A workflow should also be able to be "undeployed" in the same manner, by inverting that boolean value.

### Future Work:
A more elegant solution will involve workflow versioning by keeping a prior version of a workflow live while a revised version is in draft mode until it is ready to be published and replaces the live version with no downtime.

**Comment by symphony-soufiane** [comment]
Implemented in #133 and released in https://github.com/finos/symphony-wdk/releases/tag/1.2.0
