### ISSUE TITLE
WDK 1.2.0: BPMN Engine error when starting WDK with Conditional Branching & Loops SWADL

### ISSUE THREAD

**Issue by Kaosar-Symphony** [finos/symphony-wdk#152]
**WDK 1.2.0: BPMN Engine error when starting WDK with Conditional Branching & Loops SWADL**

### Steps to Reproduce:
1. WDK 1.2.0 & SWADL = (https://github.com/SymphonyPlatformSolutions/symphony-training-research-workflow/blob/chapter-7/workflows/research.swadl.yaml)

2. Trying to start the WDK bot - will result in a number of BPMN Engine errors.

### Expected Result:
WDK 1.2.0 is expected to start up with the SWADL for Conditional Branching & Loops being expected to work as it does in WDK 1.1.0

### Actual Result:
The WDK 1.2.0 does not start up correctly and has BPMN Engine error messages - leading to the SWADL not working or action.

### Environment:
WDK 1.2.0
SWADL = (https://github.com/SymphonyPlatformSolutions/symphony-training-research-workflow/blob/chapter-7/workflows/research.swadl.yaml)

### Additional Context:
The Chapter 7 SWADL (https://github.com/SymphonyPlatformSolutions/symphony-training-research-w...) from the WDK Course works in WDK 1.1.0 but does not work in WDK 1.2.0.
​
When starting up the WDK Bot produces this error.
​
```
2022-09-27 17:02:21.070 ERROR 7158 --- [   scheduling-1] org.camunda.bpm.engine.context           : ENGINE-16004 Exception while closing command context: ENGINE-09005 Could not parse BPMN process. Errors: 
* Invalid destination 'authoringForm' of sequence flow 'sequenceFlow_0e5cde2a-3746-4007-a84d-d28e728b2c06' | resource research-workflow.bpmn | line 166 | column 156
org.camunda.bpm.engine.ParseException: ENGINE-09005 Could not parse BPMN process. Errors: 
* Invalid destination 'authoringForm' of sequence flow 'sequenceFlow_0e5cde2a-3746-4007-a84d-d28e728b2c06' | resource research-workflow.bpmn | line 166 | column 156
```

**Comment by symphony-soufiane** [comment]
Fixed and will be released in WDK 1.3.0
![152](https://user-images.githubusercontent.com/52406574/195349030-584bc03b-7b23-4fa9-8cf1-9ebbe5f19676.png)
