### ISSUE TITLE
Workflow definition API is incomplete

### ISSUE THREAD

**Issue by opoupeney** [finos/symphony-wdk#165]
## 1. Missing ids

All event type nodes do not have id. However their ids are used in parents/children properties of activity based nodes. 

## 2. Change requests

-  2.a Activity based node "_activityId_" property should be  renamed with "_id_"

- 2.b Property "_type_" should be "SEND_MESSAGE" and "_nodeType_" should be "ACTIVITY" or for an event "MESSAGE_RECEIVED" and "EVENT" to ease the visual diagram creation.

Here is an example of what is currently returned:

`{
    "workflowId": "abcde",
    "variables": [],
    "flowNodes": [
        {
            "type": "SEND_MESSAGE_ACTIVITY",
            "parents": [
                "message-received_/onboard"
            ],
            "children": [
                "form-reply_clientForm"
            ],
            "activityId": "clientForm"
        },
        {
            "type": "UPDATE_MESSAGE_ACTIVITY",
            "parents": [
                "form-reply_clientForm"
            ],
            "children": [
                "checkGleif"
            ],
            "activityId": "progressStatus"
        },
        {
            "type": "EXECUTE_REQUEST_ACTIVITY",
            "parents": [
                "progressStatus"
            ],
            "children": [
                "resFailure",
                "resSuccess"
            ],
            "activityId": "checkGleif"
        },
        {
            "type": "UPDATE_MESSAGE_ACTIVITY",
            "parents": [
                "checkGleif"
            ],
            "children": [],
            "activityId": "resFailure"
        },
        {
            "type": "EXECUTE_SCRIPT_ACTIVITY",
            "parents": [
                "checkGleif"
            ],
            "children": [
                "statusMessage"
            ],
            "activityId": "resSuccess"
        },
        {
            "type": "UPDATE_MESSAGE_ACTIVITY",
            "parents": [
                "resSuccess"
            ],
            "children": [],
            "activityId": "statusMessage"
        },
        {
            "type": "MESSAGE_RECEIVED_EVENT",
            "parents": [],
            "children": [
                "clientForm"
            ]
        },
        {
            "type": "FORM_REPLIED_EVENT",
            "parents": [
                "clientForm"
            ],
            "children": [
                "progressStatus"
            ]
        }
    ]
}`

**Comment by symphony-soufiane** [comment]
First version will be released in WDK 1.3.0 
Gateways will be handled in a future release.

Example of response payload:
`{
    "workflowId": "data",
    "variables": {
        "loop": true
    },
    "flowNodes": [
        {
            "nodeId": "act0",
            "type": "SEND_MESSAGE",
            "group": "ACTIVITY",
            "parents": [
                "message-received_/ping"
            ],
            "children": [
                "message-received_/continue"
            ]
        },
        {
            "nodeId": "act1",
            "type": "SEND_MESSAGE",
            "group": "ACTIVITY",
            "parents": [
                "message-received_/continue",
                "act2"
            ],
            "children": [
                "act2"
            ]
        },
        {
            "nodeId": "act2",
            "type": "SEND_MESSAGE",
            "group": "ACTIVITY",
            "parents": [
                "act1"
            ],
            "children": [
                "act1"
            ]
        },
        {
            "nodeId": "message-received_/ping",
            "type": "MESSAGE_RECEIVED",
            "group": "EVENT",
            "parents": [],
            "children": [
                "act0"
            ]
        },
        {
            "nodeId": "message-received_/continue",
            "type": "MESSAGE_RECEIVED",
            "group": "EVENT",
            "parents": [
                "act0"
            ],
            "children": [
                "act1"
            ]
        }
    ]
}`
