### ISSUE TITLE
Create a Util to help generate JWTs from the WDK

### ISSUE THREAD

**Issue by richardring** [finos/symphony-wdk#175]
### Description of Problem:
Need to generate a JWT on the fly to connect to the Federation APIs (as an example) but other API may require a similar authentication token. This would be massively helpful for many customers. 

### Potential Solutions:
Make me a util. 😁 

Alternatives: Make me sad. 😢

**Comment by ystxn** [comment]
FR rejected in favour of having a fit-for-purpose draft [Federation Client](https://github.com/ystxn/wdk-federation-client).
The longer term plan is to engage Federation team to build and maintain a BDK extension similar to what was done for [Symphony Groups](https://github.com/finos/symphony-bdk-java/tree/main/symphony-bdk-extensions/symphony-group-extension). This extension will then be wrapped in custom activities by WDK. Whether it will be part of WDK core or as a separately-packaged extension is yet to be decided.
